### ISSUE TITLE
Start page view

### ISSUE THREAD

**Issue by TheMesoria** [TheMesoria/LuxBluxSoftapp#2]
We need to create some view that will show up for the user when he opens the application. It should have most of the application logic available for him from there.

This logic should contain:
- [ ]

**Comment by CarlosOlexinho** [comment]
I think this issue should be connected with issue #3, because user know's what application he's using and we don't need to show start view every time the application is started. 

I think it might look's:
At top center "welcome text",
below "welcome text" login field,
below login field, will be password field,
below password field will be login button,
and optionally a button to restart the password below it all.

Detailed arrangement of components, colors, etc. to discussion.

**Comment by n1ree** [comment]
@CarlosOlexinho is on point.

If we choose this path, company logo should be more than enough instead of welcome text. I agree with the rest.

**Comment by CarlosOlexinho** [comment]
@n1ree I  agree. It should be like in hotel or company lobby where name of this hotel or company "welcomes you". Colloquially said.

**Comment by TheMesoria** [comment]
It's most likely a duplication of #3. Let's focus effort on that one.
